CREATE TABLE `businessPlanActuals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`year` int NOT NULL,
	`category` varchar(20) NOT NULL,
	`division` varchar(50) NOT NULL,
	`subDivision` varchar(50),
	`month1` decimal(20,2) DEFAULT '0',
	`month2` decimal(20,2) DEFAULT '0',
	`month3` decimal(20,2) DEFAULT '0',
	`month4` decimal(20,2) DEFAULT '0',
	`month5` decimal(20,2) DEFAULT '0',
	`month6` decimal(20,2) DEFAULT '0',
	`month7` decimal(20,2) DEFAULT '0',
	`month8` decimal(20,2) DEFAULT '0',
	`month9` decimal(20,2) DEFAULT '0',
	`month10` decimal(20,2) DEFAULT '0',
	`month11` decimal(20,2) DEFAULT '0',
	`month12` decimal(20,2) DEFAULT '0',
	`total` decimal(20,2) DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `businessPlanActuals_id` PRIMARY KEY(`id`)
);
